<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Notima.Stride</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Stride.Engine" Version="4.3.0.2507" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\assets\data\overworld.json" Link="Content\Maps\overworld.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\assets\public-domain\julia-player-cc0.png" Link="Content\Art\julia-player-cc0.png" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\assets\public-domain\overworld-tiles-cc0.png" Link="Content\Art\overworld-tiles-cc0.png" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\assets\public-domain\julia-player-cc0.rgba" Link="Content\Art\julia-player-cc0.rgba" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\assets\public-domain\overworld-tiles-cc0.rgba" Link="Content\Art\overworld-tiles-cc0.rgba" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
